version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    volumes:
      - ./downloads:/app/downloads
      - ./bot_database.db:/app/bot_database.db
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
