services:
  # خدمة بوت التلقرام
  - type: web
    name: youtube-telegram-bot
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        sync: false
